-- ============================================================================
-- Chess Online — Turso / LibSQL (SQLite) schema
-- Run this against your Turso database using: turso db shell <db-name> < turso-schema.sql
-- ============================================================================

-- ----------------------------------------------------------------------------
-- users — app-level profile. Created by ensureProfile on first login.
-- id is a TEXT UUID generated by the backend (nanoid or crypto.randomUUID).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  display_name TEXT NOT NULL,
  avatar_url TEXT,
  role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'moderator', 'admin')),
  is_banned INTEGER NOT NULL DEFAULT 0 CHECK (is_banned IN (0, 1)),
  banned_until TEXT,
  ban_reason TEXT,
  elo INTEGER NOT NULL DEFAULT 1200 CHECK (elo BETWEEN 0 AND 4000),
  games_played INTEGER NOT NULL DEFAULT 0,
  games_won INTEGER NOT NULL DEFAULT 0,
  games_drawn INTEGER NOT NULL DEFAULT 0,
  games_lost INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_users_elo ON users (elo DESC);
CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);
CREATE INDEX IF NOT EXISTS idx_users_role ON users (role);
CREATE INDEX IF NOT EXISTS idx_users_banned ON users (is_banned) WHERE is_banned = 1;

-- Trigger to update updated_at on every update
CREATE TRIGGER IF NOT EXISTS trg_users_updated_at
  AFTER UPDATE ON users
  FOR EACH ROW
BEGIN
  UPDATE users SET updated_at = datetime('now') WHERE id = NEW.id;
END;

-- ----------------------------------------------------------------------------
-- matches — one row per finished ranked or custom-room game.
-- The server is the only writer; this is the permanent record.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS matches (
  id TEXT PRIMARY KEY,
  white_id TEXT NOT NULL,
  black_id TEXT NOT NULL,
  winner_id TEXT, -- NULL = draw
  result_type TEXT NOT NULL CHECK (result_type IN (
    'checkmate', 'resign', 'timeout', 'stalemate',
    'draw_agreement', 'threefold_repetition',
    'fifty_move_rule', 'insufficient_material', 'abandoned'
  )),
  rated INTEGER NOT NULL DEFAULT 0 CHECK (rated IN (0, 1)), -- SQLite boolean
  time_control TEXT NOT NULL,
  white_time_left_ms INTEGER NOT NULL DEFAULT 0,
  black_time_left_ms INTEGER NOT NULL DEFAULT 0,
  moves_count INTEGER NOT NULL DEFAULT 0,
  pgn TEXT NOT NULL,
  final_fen TEXT NOT NULL,
  started_at TEXT NOT NULL,
  ended_at TEXT NOT NULL,
  duration_ms INTEGER NOT NULL,
  white_elo_before INTEGER NOT NULL,
  white_elo_after INTEGER NOT NULL,
  black_elo_before INTEGER NOT NULL,
  black_elo_after INTEGER NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (white_id) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (black_id) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (winner_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_matches_white ON matches (white_id, ended_at DESC);
CREATE INDEX IF NOT EXISTS idx_matches_black ON matches (black_id, ended_at DESC);
CREATE INDEX IF NOT EXISTS idx_matches_ended_at ON matches (ended_at DESC);
CREATE INDEX IF NOT EXISTS idx_matches_rated ON matches (rated) WHERE rated = 1;

-- ----------------------------------------------------------------------------
-- user_levels — campaign progress. One row per (user, level).
-- Only upgraded (higher stars), never downgraded.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_levels (
  user_id TEXT NOT NULL,
  level_id TEXT NOT NULL,
  completed INTEGER NOT NULL DEFAULT 0 CHECK (completed IN (0, 1)),
  stars INTEGER NOT NULL DEFAULT 0 CHECK (stars BETWEEN 0 AND 3),
  best_duration_ms INTEGER,
  best_replay_id TEXT,
  attempts INTEGER NOT NULL DEFAULT 1,
  last_attempt_at TEXT NOT NULL DEFAULT (datetime('now')),
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (user_id, level_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_user_levels_user ON user_levels (user_id);

-- ----------------------------------------------------------------------------
-- level_replays — every campaign attempt (for replay and anti-cheat).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS level_replays (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  level_id TEXT NOT NULL,
  pgn TEXT NOT NULL,
  final_fen TEXT NOT NULL,
  moves_count INTEGER NOT NULL,
  duration_ms INTEGER NOT NULL,
  completed INTEGER NOT NULL CHECK (completed IN (0, 1)),
  suspicious INTEGER NOT NULL DEFAULT 0 CHECK (suspicious IN (0, 1)),
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_level_replays_user_level 
  ON level_replays (user_id, level_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_level_replays_suspicious 
  ON level_replays (suspicious) WHERE suspicious = 1;

-- Add foreign key for best_replay_id after level_replays exists
-- Note: SQLite doesn't support ALTER TABLE ADD CONSTRAINT, so this must be in the initial schema

-- ----------------------------------------------------------------------------
-- room_logs — audit trail of live rooms (in-memory GameRoom tracking).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS room_logs (
  id TEXT PRIMARY KEY,
  room_id TEXT NOT NULL UNIQUE,
  mode TEXT NOT NULL CHECK (mode IN ('ranked', 'custom', 'campaign')),
  white_id TEXT,
  black_id TEXT,
  match_id TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  ended_at TEXT,
  FOREIGN KEY (white_id) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (black_id) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_room_logs_created_at ON room_logs (created_at DESC);

-- ----------------------------------------------------------------------------
-- chat_logs — in-room chat (moderation/abuse review).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS chat_logs (
  id TEXT PRIMARY KEY,
  room_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  message TEXT NOT NULL CHECK (length(message) <= 300),
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_chat_logs_room ON chat_logs (room_id, created_at);

-- ----------------------------------------------------------------------------
-- spectator_logs — who watched which room.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS spectator_logs (
  id TEXT PRIMARY KEY,
  room_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  joined_at TEXT NOT NULL DEFAULT (datetime('now')),
  left_at TEXT,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_spectator_logs_room ON spectator_logs (room_id);
CREATE INDEX IF NOT EXISTS idx_spectator_logs_user ON spectator_logs (user_id);

-- ----------------------------------------------------------------------------
-- campaign_levels — định nghĩa các level campaign (admin tạo)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS campaign_levels (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  difficulty TEXT NOT NULL CHECK (difficulty IN ('beginner', 'intermediate', 'advanced', 'expert')),
  order_index INTEGER NOT NULL UNIQUE,
  initial_fen TEXT NOT NULL,
  target_objective TEXT NOT NULL, -- 'checkmate_in_3', 'win_material', etc.
  time_limit_ms INTEGER,
  star_thresholds TEXT NOT NULL, -- JSON: {"1": 60000, "2": 45000, "3": 30000}
  ai_level INTEGER NOT NULL DEFAULT 1200 CHECK (ai_level BETWEEN 800 AND 2800),
  is_published INTEGER NOT NULL DEFAULT 0 CHECK (is_published IN (0, 1)),
  created_by TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_campaign_levels_order ON campaign_levels (order_index);
CREATE INDEX IF NOT EXISTS idx_campaign_levels_published ON campaign_levels (is_published) WHERE is_published = 1;

-- Trigger to update updated_at on campaign_levels
CREATE TRIGGER IF NOT EXISTS trg_campaign_levels_updated_at
  AFTER UPDATE ON campaign_levels
  FOR EACH ROW
BEGIN
  UPDATE campaign_levels SET updated_at = datetime('now') WHERE id = NEW.id;
END;

-- ============================================================================
-- NOTES:
-- - SQLite doesn't have native UUID type, use TEXT with app-generated UUIDs
-- - SQLite doesn't have native BOOLEAN, use INTEGER with CHECK (0, 1)
-- - SQLite doesn't support Row Level Security (handle authorization in app)
-- - Use datetime('now') for timestamps instead of PostgreSQL's now()
-- - Foreign key constraints are enforced if PRAGMA foreign_keys = ON
-- ============================================================================
